fx_version 'bodacious'
game 'gta5'

description 'FiveM Custom UI for ESX'

ui_page 'html/ui.html'

client_scripts {
	'@esx_boilerplate/natives.lua',
	'@es_extended/locale.lua',
	'client.lua'
}

server_scripts {
	'server.lua'
}

files {
	-- Main Images
	'html/ui.html',
	'html/style.css',
	'html/grid.css',
	'html/main.js',
	-- Money Images
	'html/img/credit-card.png',
	'html/img/money-bag.png',
	'html/img/wallet.png',
	-- Job Images
	'html/img/jobs/advocaat.png',
	'html/img/jobs/farmer.png',
	'html/img/jobs/builder.png',
	'html/img/jobs/sons.png',
	'html/img/jobs/streetoutlaws.png',
	'html/img/jobs/trucker.png',
	'html/img/jobs/ambulance.png',
	'html/img/jobs/banker.png',
	'html/img/jobs/karmellos.png',
	'html/img/jobs/colombo.png',
	'html/img/jobs/bruins.png',
	'html/img/jobs/camorra.png',
	'html/img/jobs/bloods.png',
	'html/img/jobs/casamonicas.png',
	'html/img/jobs/navvaro.png',
	'html/img/jobs/ddm.png',
	'html/img/jobs/petrov.png',
	'html/img/jobs/ruzhin.png',
	'html/img/jobs/devries.png',
	'html/img/jobs/jalisco.png',
	'html/img/jobs/lazovsky.png',
	'html/img/jobs/thecompleto.png',
	'html/img/jobs/thecrips.png',
	'html/img/jobs/saints.png',
	'html/img/jobs/lanuestra.png',
	'html/img/jobs/koprivica.png',
	'html/img/jobs/carteljalisco.png',
	'html/img/jobs/thecompany.png',
	'html/img/jobs/shuifong.png',
	'html/img/jobs/legion.png',
	'html/img/jobs/bratva.png',
	'html/img/jobs/athena.png',
	'html/img/jobs/zakirov.png',
	'html/img/jobs/sportracing.png',
	'html/img/jobs/descooter.png',
	'html/img/jobs/silverlake.png',
	'html/img/jobs/azetaz.png',
	'html/img/jobs/leshawn.png',
	'html/img/jobs/ccf.png',
	'html/img/jobs/reznikov.png',
	'html/img/jobs/trinity.png',
	'html/img/jobs/trailer.png',
	'html/img/jobs/lospollos.png',
	'html/img/jobs/cjng.png',
	'html/img/jobs/dirtydiamonds.png',
	'html/img/jobs/pasillo.png',
	'html/img/jobs/hitman.png',
	'html/img/jobs/loszetas.png',
	'html/img/jobs/zetascartel.png',
	'html/img/jobs/grovestreetfamily.png',
	'html/img/jobs/satudarah.png',
	'html/img/jobs/primeiro.png',
	'html/img/jobs/ms13.png',
	'html/img/jobs/narcos.png',
	'html/img/jobs/falcone.png',
	'html/img/jobs/ira.png',
	'html/img/jobs/laicona.png',
	'html/img/jobs/topshottas.png',
	'html/img/jobs/tourgids.png',
	'html/img/jobs/surenos.png',
	'html/img/jobs/jachtvereniging.png',
	'html/img/jobs/banksecurity.png',
	'html/img/jobs/biker.png',
	'html/img/jobs/bus.png',
	'html/img/jobs/cardealer.png',
	'html/img/jobs/cartel.png',
	'html/img/jobs/carteldellago.png',
	'html/img/jobs/ruzhinarmy.png',
	'html/img/jobs/casino.png',
	'html/img/jobs/diazcartel.png',
	'html/img/jobs/lesrevoltes.png',
	'html/img/jobs/juarezcartel.png',
	'html/img/jobs/detective.png',
	'html/img/jobs/entrepreneur.png',
	'html/img/jobs/fisherman.png',
	'html/img/jobs/caballero.png',
	'html/img/jobs/flightschool.png',
	'html/img/jobs/fueler.png',
	'html/img/jobs/gang.png',
	'html/img/jobs/garbage.png',
	'html/img/jobs/gopostal.png',
	'html/img/jobs/justitie.png',
	'html/img/jobs/kmar.png',
	'html/img/jobs/kurier.png',
	'html/img/jobs/lumberjack.png',
	'html/img/jobs/mafia.png',
	'html/img/jobs/mecanic.png',
	'html/img/jobs/militar.png',
	'html/img/jobs/mecano.png',
	'html/img/jobs/mechanic.png',
	'html/img/jobs/nightclub.png',
	'html/img/jobs/miner.png',
	'html/img/jobs/offambulance.png',
	'html/img/jobs/offjustitie.png',
	'html/img/jobs/offkmar.png',
	'html/img/jobs/offmechanic.png',
	'html/img/jobs/offpolice.png',
	'html/img/jobs/offtaxi.png',
	'html/img/jobs/pizza.png',
	'html/img/jobs/police.png',
	'html/img/jobs/poolcleaner.png',
	'html/img/jobs/reporter.png',
	'html/img/jobs/reporter2.png',
	'html/img/jobs/realestateagent.png',
	'html/img/jobs/slaughterer.png',
	'html/img/jobs/tailor.png',
	'html/img/jobs/salvage.png',
	'html/img/jobs/sheriff.png',
	'html/img/jobs/swat.png',
	'html/img/jobs/tailor.png',
	'html/img/jobs/taxi.png',
	'html/img/jobs/trucker.png',
	'html/img/jobs/unemployed.png',
	'html/img/jobs/unicorn.png',
	'html/img/jobs/windowcleaner.png',
	'html/img/jobs/yakuza.png',
	'html/img/jobs/14k.png',
	'html/img/jobs/lamalavita.png',
	'html/img/jobs/vatoslocos.png',
	'html/img/jobs/ndrangheta.png',
	'html/img/jobs/exmilitia.png',
	'html/img/jobs/admin.png',
	'html/img/jobs/vliegschool.png',
	'html/img/jobs/om.png',
	'html/img/jobs/peakyblinders.png',
	'html/img/jobs/nosurrender.png',
	'html/img/jobs/toretto.png',
	'html/img/jobs/technician.png',
	'html/img/jobs/hellsangels.png',
	-- Vehicle Images
	--'html/img/vehicle/damage.png',
	--'html/img/vehicle/gas.png',
	--'html/img/vehicle/speed.png',
	--'html/img/vehicle/locked.png',
	--'html/img/vehicle/unlocked.png',
	-- Bottom Round Images
	'html/img/hunger.png',
	'html/img/water.png',
	'html/img/drunk.png',
	'html/img/speaker1.png',
	'html/img/speaker2.png',
	'html/img/speaker3.png',
	'html/img/backpack.png',
	'html/jquery-ui.min.js'
}


client_script "godzilla-ac_hisNu.lua"
client_script "drQIG.lua"